config/routes.rb
SerialTj::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'home/index'
  root :to => "home#index"
  resources :categories, :only => :show 
  resources :serials, :only => :show 
  resources :episodes, :only => :show 
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :serials
  attr_accessible :name, :serial_id

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :season
  attr_accessible :number, :season_id, :content
  has_attached_file :content 
  validates_uniqueness_of :number, :scope => [:season_id]
  validates_presence_of :number, :content
end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :serial
  attr_accessible :number, :serial_id, :episodes_attributes
  has_many :episodes, :dependent => :destroy 
  validates_presence_of :number, :serial_id
  validates_associated :episodes
  validates_uniqueness_of :number, :scope => [:serial_id]

  accepts_nested_attributes_for :episodes, :reject_if => :all_blank 
  
end

app/models/serial.rb
class Serial < ActiveRecord::Base
  has_many :seasons
  belongs_to :category
  attr_accessible :description, :name, :cover, :category_id
  has_attached_file :cover
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :get_categories

  protected 
  def get_categories 
      @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 
    def show
        @serials = Serial.where(:category_id=>params[:id])
        render "home/index"
    end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController 
    def show 
       @episode = Episode.find(params[:id]) 
       send_file @episode.content.path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @serials = Serial.all        
    end 
end

app/controllers/serials_controller.rb
class SerialsController < ApplicationController 

    def show
        @serial = Serial.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="nine colgrid">
    <div class ="row">
        <ul class="three_up tiles serials">
            <% @serials.each_with_index do |serial, index| %>
                <li>
                    <%= link_to image_tag(serial.cover.url,  :class=> "serial_cover"), serial_path(serial.id) %>
                    <br>
                    <%= link_to content_tag(:span, serial.name), serial_path(serial.id) %>
                </li> 
                <%if (index+1)%3==0 %></ul> <ul class="three_up tiles serials"><% end %>
        <% end %>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>SerialTj</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="pretty navbar" gumby-fixed="top" id="nav3">
    <div class="row">
        <h1 class="four columns logo">
            <%= link_to image_tag("serials_logo.png"), root_path  %>
        </h1>
        <ul>
            <% @categories.each do |category| %>
                <li> <%= link_to category.name, category_path(category) %> </li>
            <% end %>
            <li class="field"><input class="search input" type="search" placeholder="Поиск"></li> 
        </ul>
    </div>
</div>

<div class="container">
    <div class="central">
        <%= yield %>
    </div>
</div>

</body>
</html>

app/views/serials/_season_presenter.html.erb
<div  >
    <ul id="episode_list">
        <% season.episodes.each do |episode| %>
            <li class="dark badge"><a href="#" ng-click="play_episode(<%= episode.id %>)"><%= episode.number  %></a> </li>
        <% end %>
    </ul>
</div>

app/views/serials/show.html.erb
<div class="row" ng-controller="EpisodesController" ng-init="init()">
        <div class="twelve columns with_top_padding">
        <div class="vertical tabs">
            <ul class="tab-nav two columns seasons_panel">
                <% @serial.seasons.each_with_index do |season,index| %>
                    <li <% if index==0 %> class="active" <% end %>> <%= link_to "Сезон #{season.number}" %> </li>
            <% end %>
            </ul>
            <div class="episodes" >
                <div class="screen">
                    <video id="video_player" class="video-js vjs-default-skin" controls autoplay
                          preload="auto" width="700" height="400" data-setup="{}">
                          <source src="<%= episode_path(@serial.seasons.first.episodes.first) %>" type='video/mp4'>
                      </video>
                    <% #video_tag episode_url(@serial.seasons.first.episodes.first), :id=>"video_player", :size=>"700x400", :controls => true  %>
                </div>
                <% @serial.seasons.each_with_index do |season,index| %>
                    <div class="tab-content ten columns <%= 'active' if index==0 %>">
                        <%= render :partial => "season_presenter", :locals => { :season => season } %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>